export const Error="Error"
export const getAllCategories="getAllCategories"
export const Create_Category="Create_Category"
export const getAllBrands="getAllBrands"
export const Create_Brand="Create_Brand"