export const Error="Error"
export const getAllCategories="getAllCategories"
export const Create_Category="Create_Category"
export const getAllBrands="getAllBrands"
export const Create_Brand="Create_Brand"
export const Create_Subcategory="Create_Subcategory"
export const Get_Subcategory="Get_Subcategory"
export const Create_Products="Create_Products"